### ISSUE TITLE
Memory leak in tmp folder for long-running parallel process!

### ISSUE THREAD

**Issue by EagleoutIce** [Code-Inspect/flowr#395]

**Comment by EagleoutIce** [comment]
we have a lot of `.R` files and many `Rtmp` folders when running parallel tasks!

**Comment by EagleoutIce** [comment]
We still need a way to automatically unlink the (maybe empty) tempdir!

**Comment by EagleoutIce** [comment]
Still exists on failed parse requests!

**Comment by EagleoutIce** [comment]
Maybe, because the shell fails to parse and the recovery causes memory leak (on the read socket?)

**Comment by EagleoutIce** [comment]
Correction: there are just files that are that big (or the DF extraction itself has the leak!).

Investigate: 

```
[["--input","/home/limerent/CRAN/xbreed/R/Make_cross_v11_Commented.R","--output-dir","/home/limerent/Second-Sun/flowr-run-out-3/--xbreed／R／Make_cross_v11_Commented.R","--features","usedPackages","--features","comments","--features","definedFunctions","--features","usedFunctions","--features","values","--features","assignments","--features","loops","--features","controlflow","--features","dataAccess","--features","expressionList","--features","variables","--compress"],["--input","/home/limerent/CRAN/wiseR/inst/bn/server.R","--output-dir","/home/limerent/Second-Sun/flowr-run-out-3/--wiseR／inst／bn／server.R","--features","usedPackages","--features","comments","--features","definedFunctions","--features","usedFunctions","--features","values","--features","assignments","--features","loops","--features","controlflow","--features","dataAccess","--features","expressionList","--features","variables","--compress"],["--input","/home/limerent/CRAN/visvow/R/visvow.R","--output-dir","/home/limerent/Second-Sun/flowr-run-out-3/--visvow／R／visvow.R","--features","usedPackages","--features","comments","--features","definedFunctions","--features","usedFunctions","--features","values","--features","assignments","--features","loops","--features","controlflow","--features","dataAccess","--features","expressionList","--features","variables","--compress"],["--input","/home/limerent/CRAN/tukeytrend/inst/doc/ExamplesTukeytrendtest.R","--output-dir","/home/limerent/Second-Sun/flowr-run-out-3/example---tukeytrend／inst／doc／ExamplesTukeytrendtest.R","--features","usedPackages","--features","comments","--features","definedFunctions","--features","usedFunctions","--features","values","--features","assignments","--features","loops","--features","controlflow","--features","dataAccess","--features","expressionList","--features","variables","--compress"],["--input","/home/limerent/CRAN/torch/R/RcppExports.R","--output-dir","/home/limerent/Second-Sun/flowr-run-out-3/--torch／R／RcppExports.R","--features","usedPackages","--features","comments","--features","definedFunctions","--features","usedFunctions","--features","values","--features","assignments","--features","loops","--features","controlflow","--features","dataAccess","--features","expressionList","--features","variables","--compress"],["--input","/home/limerent/CRAN/tidyRSS/tests/testthat/www.r-statistics.com/feed.R","--output-dir","/home/limerent/Second-Sun/flowr-run-out-3/test---tidyRSS／tests／testthat／www.r-statistics.com／feed.R","--features","usedPackages","--features","comments","--features","definedFunctions","--features","usedFunctions","--features","values","--features","assignments","--features","loops","--features","controlflow","--features","dataAccess","--features","expressionList","--features","variables","--compress"],["--input","/home/limerent/CRAN/tidyRSS/tests/testthat/fivethirtyeight.com/all/feed.R","--output-dir","/home/limerent/Second-Sun/flowr-run-out-3/test---tidyRSS／tests／testthat／fivethirtyeight.com／all／feed.R","--features","usedPackages","--features","comments","--features","definedFunctions","--features","usedFunctions","--features","values","--features","assignments","--features","loops","--features","controlflow","--features","dataAccess","--features","expressionList","--features","variables","--compress"],["--input","/home/limerent/CRAN/stpm/R/hes_spm_g.r","--output-dir","/home/limerent/Second-Sun/flowr-run-out-3/--stpm／R／hes_spm_g.r","--features","usedPackages","--features","comments","--features","definedFunctions","--features","usedFunctions","--features","values","--features","assignments","--features","loops","--features","controlflow","--features","dataAccess","--features","expressionList","--features","variables","--compress"],["--input","/home/limerent/CRAN/spmoran/R/resf_vc.R","--output-dir","/home/limerent/Second-Sun/flowr-run-out-3/--spmoran／R／resf_vc.R","--features","usedPackages","--features","comments","--features","definedFunctions","--features","usedFunctions","--features","values","--features","assignments","--features","loops","--features","controlflow","--features","dataAccess","--features","expressionList","--features","variables","--compress"],["--input","/home/limerent/CRAN/rpact/tests/testthat/test-f_design_sample_size_calculator.R","--output-dir","/home/limerent/Second-Sun/flowr-run-out-3/test---rpact／tests／testthat／test-f_design_sample_size_calculator.R","--features","usedPackages","--features","comments","--features","definedFunctions","--features","usedFunctions","--features","values","--features","assignments","--features","loops","--features","controlflow","--features","dataAccess","--features","expressionList","--features","variables","--compress"],["--input","/home/limerent/CRAN/regplot/R/regplot.R","--output-dir","/home/limerent/Second-Sun/flowr-run-out-3/--regplot／R／regplot.R","--features","usedPackages","--features","comments","--features","definedFunctions","--features","usedFunctions","--features","values","--features","assignments","--features","loops","--features","controlflow","--features","dataAccess","--features","expressionList","--features","variables","--compress"],["--input","/home/limerent/CRAN/polymapR/R/r6_functions.R","--output-dir","/home/limerent/Second-Sun/flowr-run-out-3/--polymapR／R／r6_functions.R","--features","usedPackages","--features","comments","--features","definedFunctions","--features","usedFunctions","--features","values","--features","assignments","--features","loops","--features","controlflow","--features","dataAccess","--features","expressionList","--features","variables","--compress"]]
```

**Comment by EagleoutIce** [comment]
Still there on: 

```
[0/78401] Running next, currently running: 1, queue: 78400 [args: --input /home/limerent/CRAN/xbreed/R/Make_cross_v11_Commented.R --output-dir /home/limerent/Second-Sun/flowr-run-out-3/--xbreed／R／Make_cross_v11_Commented.R --features usedPackages --features comments --features definedFunctions --features usedFunctions --features values --features assignments --features loops --features controlflow --features dataAccess --features expressionList --features variables --compress]
[0/78401] Running next, currently running: 2, queue: 78399 [args: --input /home/limerent/CRAN/wiseR/inst/bn/server.R --output-dir /home/limerent/Second-Sun/flowr-run-out-3/--wiseR／inst／bn／server.R --features usedPackages --features comments --features definedFunctions --features usedFunctions --features values --features assignments --features loops --features controlflow --features dataAccess --features expressionList --features variables --compress]
[0/78401] Running next, currently running: 3, queue: 78398 [args: --input /home/limerent/CRAN/visvow/R/visvow.R --output-dir /home/limerent/Second-Sun/flowr-run-out-3/--visvow／R／visvow.R --features usedPackages --features comments --features definedFunctions --features usedFunctions --features values --features assignments --features loops --features controlflow --features dataAccess --features expressionList --features variables --compress]
[0/78401] Running next, currently running: 4, queue: 78397 [args: --input /home/limerent/CRAN/tukeytrend/inst/doc/ExamplesTukeytrendtest.R --output-dir /home/limerent/Second-Sun/flowr-run-out-3/example---tukeytrend／inst／doc／ExamplesTukeytrendtest.R --features usedPackages --features comments --features definedFunctions --features usedFunctions --features values --features assignments --features loops --features controlflow --features dataAccess --features expressionList --features variables --compress]
[0/78401] Running next, currently running: 5, queue: 78396 [args: --input /home/limerent/CRAN/torch/R/RcppExports.R --output-dir /home/limerent/Second-Sun/flowr-run-out-3/--torch／R／RcppExports.R --features usedPackages --features comments --features definedFunctions --features usedFunctions --features values --features assignments --features loops --features controlflow --features dataAccess --features expressionList --features variables --compress]
```

**Comment by EagleoutIce** [comment]
Result:

String-lenghts beyound the node limit:

```
/home/limerent/GitHub/phd/flowr/dist/src/core/print/dataflow-printer.js:29
                    elems.push([key, `[${[...value].map(([k, v]) => `[${mayObjectJson(k)},${mayObjectJson(v)}]`).join(',')}]`]);
                                                                                                                 ^

RangeError: Invalid string length
    at Array.join (<anonymous>)
    at objectJson (/home/limerent/GitHub/phd/flowr/dist/src/core/print/dataflow-printer.js:29:114)
    at objectJson (/home/limerent/GitHub/phd/flowr/dist/src/core/print/dataflow-printer.js:32:38)
    at dataflowGraphToJson (/home/limerent/GitHub/phd/flowr/dist/src/core/print/dataflow-printer.js:47:12)
    at printStepResult (/home/limerent/GitHub/phd/flowr/dist/src/core/steps.js:85:12)
    at getStatsForSingleFile (/home/limerent/GitHub/phd/flowr/dist/src/cli/statistics-helper-app.js:66:112)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
